name: FartherViewDistance
version: $version
main: xuan.cat.fartherviewdistance.code.ChunkIndex
api-version: "26.1"
authors: [xuancat0208, EuSouVoce, Lumine1909, Mapacheee, just_lofe, HauserGrim]
folia-supported: true
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false # PlaceholderAPI is optional, so we set it to false.
